---

- name: Set fact for NIC name
  set_fact:
    nic: 'ens4'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Configure 2nd NIC for Ceph network
  shell: |
    cat << _EOF > /etc/network/interfaces.d/50-ceph-net.cfg
     auto {{ nic }}
     iface {{ nic }}  inet dhcp
     _EOF
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Bring up interface
  shell: ifup '{{ nic }}' 
      
